site_name: Hack-Wiki-Commands
nav:
    - Home: index.md
    - About: about.md
    - Persistence:
        - 'Schtasks': 'Persistence/schtask.md'
    - Wifi:
        - 'Wlan Extract Pass': 'Wifi/Wlan_Extract_Info/wlanExtractIndo.md'
        - 'Config Wifi Linux': 'Wifi/WlanConfig/configWifi.md'
        - 'Weak Routes': 'Wifi/Airckark/wifi_hack_tecnics.md'
    - Aircrack-ng:
        - 'Karma': 'Wifi/Airckark/karmaHAKK.md'
        - 'Aircrak Commands': 'Wifi/Airckark/aircrack_comands.md'
        - 'Evil Twing': 'Wifi/Airckark/Evil_tiwn.md'
    - Android:
        - 'Analysis Methodology': 'Android/android-MetodologiaAnalisis.md'
theme: readthedocs
